name: volkamerlab-covid
channels:
  - conda-forge
  - defaults
  - omnia
dependencies:
  - python >=3.6
  - pip
  - jupyter
  - notebook
  - pandas
  - rdkit
  - numpy
  - biopython
  - chembl_webresource_client
  - matplotlib-base
  - tqdm
  - openforcefield
